### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by DSeyka** [BGforgeNet/Fallout2_NPC_Armor#1]
Hello and first of all, thank you for keeping Unofficial Patch updated! I sure do appreciate it.
The NPC armor mod doesn't seem to be working for me though. I have Unofficial Patch Updated (v14) and FO2Tweaks installed, and both of these are working just fine. Armor mod, well, just doesn't. Any ideas why that would be the case? The only thing I can think of is that I've started the game without u14, fo2tweaks or npc armor mod enabled, and only applied them later on. But none of my NPCs are showing up in armor.
Here's a savegame where all my party members have armor equipped but their sprites are unchanged: https://gofile.io/d/ozDETU
Thank you in advance for looking into it and again for keeping UP alive. :)

**Comment by burner1024** [comment]
> Here's a savegame

where?

**Comment by DSeyka** [comment]
I've added the link, also attached the ddraw.ini file in case I've messed something up in there. But I don't think I did because FO2Tweaks work fine.

**Comment by burner1024** [comment]
Yes, I can reproduce.
Strange, the script reports missing FID. I thought it's enough to just make sure the files exists, but perhaps I'm missing something about fids.
Edit: I'm stupid, apparatenly fids got their own list... Not sure if it's possible to make the mod pluggable then.

**Comment by DSeyka** [comment]
So it's because I didn't start a new game with it enabled? Oh well, I'll make sure to install it first next time I'm playing then. Thank you for your time, no big deal if there's no way for it to work on my current game, feel free to close this.

Probably worth mentioning in the documentation that user needs to start a new game though!

**Comment by burner1024** [comment]
No, it's nothing to do with how you started it. Hang tight for now.

**Comment by burner1024** [comment]
@DSeyka for the time being, you can grab [critters.lst](https://github.com/BGforgeNet/Fallout2_Restoration_Project/raw/master/data/art/critters/critters.lst) from RP and drop it into `data/art/critters`. Also make sure to set `IniConfigFolder=mods` in `ddraw.ini`.

@FakelsHub @NovaRain any idea how to make this pluggable ( = working on any game without shipping a separate packages for each)? Or, worst case, would there be any side effects if I just ship `critters.lst` from RP, so it works on both UP and RP without modification?

**Comment by DSeyka** [comment]
Thanks! It works now, very much appreciated. 👍
Won't be closing this issue then, do it yourself as applicable.

**Comment by FakelsHub** [comment]
Непонятно в чем проблема, в неправильном critters.lst ?

**Comment by burner1024** [comment]
Его вообще не было, так что дефолтный использовался. Вопрос в том, можно ли сделать, чтобы подключался мод куда угодно, или все-таки придется каждой игре свой critters.lst.
И если придется каждой отдельно, то хотя бы для UP можно взять lst от RP или какие-нибудь странные побочки пойдут.

**Comment by FakelsHub** [comment]
Куда угодно - нет конечно, у нас движек не с открытыми исходниками(вернее из совсем нет) чтобы взять так просто и сделать.
А есть какая либо разница между UP & RP lst?

**Comment by burner1024** [comment]
вот такая разница
```diff
--- up.lst	2020-06-13 22:28:06.982239289 +0700
+++ rp.lst	2019-08-01 15:17:56.026709011 +0700
@@ -7,7 +7,7 @@
 hfmaxx,11,1
 hfmetl,11,1
 hmbjmp,11
-hmbmet,11
+hmbmet,11,1
 hmcmbt,11,1
 hmjmps,11,1
 hmlthr,11,1
@@ -101,3 +101,51 @@
 madeth,100
 magunn,101
 mabos2,102
+mawasp,103,1
+haenro,11,1
+nmsulj,11,1
+nmsuca,11,1
+nmsuma,11,1
+nmsupa,11,1
+nmsula,11,1
+nmcaca,11,1
+nmcama,11,1
+nmcapa,11,1
+nmvilj,11,1
+nmvica,11,1
+nmvima,11,1
+nmvipa,11,1
+nmvila,11,1
+maadog,16
+malieu,21
+nfchld,27,1
+NMSOLO
+NMBOBA
+NMCHEW
+NMVADE
+MAJABA
+MAR2D2
+MAC3PO
+NMYODA
+NAROYA
+nmmaxz,11,1
+nmltbb,11,1
+nmmetb,11,1
+nmmypa,11,1
+nmmyca,11,1
+nmcalj,11,1
+nmjmpb,11,1
+nmprmb,11,1
+nmcana,11,1
+nmkrom,11,1
+reserv,65
+reserv,80
+maplnr,65
+mardog,16,1
+marobb,66
+nmmax8,11,1
+LAGHUL,11,1
+NAGPLT,11,1
+HMBOXS,11,1
+HMBOXL,11,1
+HMBOXB,11,1
```

**Comment by FakelsHub** [comment]
если от PR > UP то ничего страшного не случится.
