### ISSUE TITLE
Graphical glitches when installed with Fallout Et tu (aka Fallout1in2)

### ISSUE THREAD

**Issue by zpangwin** [BGforgeNet/Fallout2_NPC_Armor#4]
In case it is helpful to others, I just wanted to note that there appears to be a graphical glitch that occurs when this mod is used with [Fallout Et tu](https://github.com/rotators/Fo1in2) (aka Fallout1in2 or Fo1in2)

I am not really expecting any sort of resolution, unless the someone wants to simply add a note to the README.md explicitly noting this as a known issue. There is already the following line in README.md.

> To work with other games based on F2 engine, it'll require additional configuration in mods/npc_armor.ini, and [critters.lst](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/art/critters/critters.lst) (which might not be the task for the faint of heart).

Which is what I believe is happening since I am using the defaults for both Fo1in2 and this mod.

I am mostly filing this for the sake of documentation in case any one else starts getting weird stuff in their game, then they might be able to figure it out from a simple google search. What I have noticed is that when both mods are installed and you are launching via the Fo1in2 launcher, that both the Vault 13 overseer as well as Gizmo in the Junk Town Casino appear as some sort of weird lava man / flame elemental looking sort of thing (it has a black smiley face and it's eyes blink lol... guessing it is some sort of placeholder texture or something). I have also noticed that one (but not all) of the children in Shady Sands was replaced with an adult that looked to be wearing a tuxedo... but still acted like a child (ran around town / same dialog / pickpocketing only had rocks / same taunts when caught pickpocketing / etc). I only thought to take a screenshot when I saw it the 2nd time with Gizmo.

Anyway, here are steps to recreate:

1. Install FO2 and FO1 (I used the latest GOG versions for both)
2. Install [Fallout Et tu](https://github.com/rotators/Fo1in2) per instructions on their page. I used Fallout1in2 v1.8.3032
3. I also replaced the included ddraw.dll with the [v4.3.7](https://sourceforge.net/projects/sfall/files/sfall/) (I see 4.3.8 was just released but it hadn't been when I began testing). Fo1in2 came with v4.3.6 and I had not yet gotten around to customizing the ini in this particular install (tho Fo1in2 does tweak a few things vs the sfall defaults).
4. There was already a folder at `<FO2 install dir>\Fallout1in2\mods` so I just added the extracted (and unmodified) `npc_armor.dat` and `npcarmor.ini` files to this folder.

Normal Gizmo:
![fo1in2-gizmo-normally](https://user-images.githubusercontent.com/29719631/229313858-4e4b1385-6ad3-4f9f-b3eb-4a7c8648beb0.png)

Gizmo w both mods installed:
![fo1in2-gizmo-w-npcarmor](https://user-images.githubusercontent.com/29719631/229313874-a4f364ec-5e11-416b-9a1e-c622aa855442.png)

Fo1in2 defaults:
[ddraw.ini.txt](https://github.com/BGforgeNet/Fallout2_NPC_Armor/files/11130598/ddraw.ini.txt)
[sfall-mods.ini.txt](https://github.com/BGforgeNet/Fallout2_NPC_Armor/files/11130600/sfall-mods.ini.txt)

Note also that this doesn't really impact gameplay in any way... (aside from immersion / me not being able to see his desk when trying to pickpocket him). It appears to be a purely graphical issue only.

Workarounds:

* Pretend they have turned into flame elementals / demons / lava men / whatever
* Don't use the 2 mods at the same time (deleting `npc_armor.dat` and `npcarmor.ini` from the `<FO2 install dir>\Fallout1in2\mods`  folder and reloading fixes it for me)

**Comment by Lexx2k** [comment]
NPC armor mod is integrated into ettu by default. Sadly you broke your game for nothing.

**Comment by zpangwin** [comment]
@Lexx2k 

> NPC armor mod is integrated into ettu by default. Sadly you broke your game for nothing.

Fair enough; I most certainly did just that. Looking back through Ettu's Readme.md I do see the bullet point for `Party members level up and change their appearance based on worn armor.` now which I had either previously missed or maybe saw but it just didn't really register that this meant it was doing the same thing as NPC Armor mod (even though it probably should have).

Still, like I said, mostly I just wanted to document somewhere in case someone else did the same dumb thing that it would make it obvious what the issue was and how to resolve it. Apologies if I posted to the wrong place or otherwise wasted your and/or burner1024's time, as that was not my intent. And thank you both for your excellent mods! I've really been enjoying Et tu so far.
