### ISSUE TITLE
''Cat'' Jules wrong skin cvolor when wearing combat armor 

### ISSUE THREAD

**Issue by CrankyBonesGaming** [BGforgeNet/Fallout2_NPC_Armor#5]
im playing the latest rpu and Cat jules has the wrong grafic frm when using combat armor so ge has a white person face and neck

**Comment by burner1024** [comment]
Please attach screenshot and savegame.

**Comment by NovaRain** [comment]
Try unequipping his combat armor first, save the game, then change `Combat=16777226` to **`Combat=16777367`** in npcarmor.ini. Now he should have correct skin color when wearing combat armor.

**Comment by CrankyBonesGaming** [comment]
NovaRain is right. Hopefully this will be standardized in future updates. As i understand it there is suposed to be a unique Robe frm set from "Blackdude" aswell and i wonder what id number that had if possible. Also Thanks NovaRain

**Comment by burner1024** [comment]
You'll need to add frms, then modify critter.lst, then npcarmor.ini.

**Comment by burner1024** [comment]
The number would be `0x1000000 + 153 - 1  = 16777368`.
